### PR TITLE
WIP: TYPO3 v8 Compatibility

### PR DESCRIPTION
**Pull request by verdure-peuser**
Hi,

since we needed the forum in a v8 LTS project we updated all necessary code parts needed for our integration. We don't use every feature right now, most of the viewhelpers are not touched since we use our own (Breadcrumbs, Rootlines, Avatars/User-Information). This is still work in progress and not finished but a first step. At the moment posting/editing, listing of forums and moderation works including helpful posts.

Warning: We haven't used this in TYPO3 6/7 nor tested it

Feel free to use the parts we already provided, or maybe pick the ones you want, or suggest a different approach ?-)

### CODE REVIEW

**Comment by sigma67** [comment]
I just tried this PR on my Typo3 8 installation. Unfortunately it seems that the Typoscript Setup settings (e.g. settings.pids.forum) are not loaded and therefore the views don't work correctly. 
Any idea why this might happen? I cloned an existing Typo3 7 installation and replaced the plugin, so the Typoscript is definitely set up correctly.

There is also an issue with the Bootstrap Default Layout (Resources\Private\Layouts\Bootstrap\Default.html). The flash messages line
`<f:flashMessages class="alert alert-success" renderMode="div" />`
no longer works in Typo3 8.

**Comment by verdure-peuser** [comment]
@sigma67 are you using v8 oder v7 ? You wrote both versions ;) We used this in a TYPO3 v8, Haven't tested it at all in v7. Have you setup all constants properly ? Check in object manager if the constants are set and properly declared in your setup. We defined all constants and setup in a own file. Since we used Foundation in our project there can maybe some issues in the bootstrap templates, we only used the default ones.

**Comment by sigma67** [comment]
@verdure-peuser I have been using typo3_forum with Typo3 7 in the past, which worked fine.
Now I'm migrating to Typo3 v8, which this post is about. I set up a copy of the old instance and replaced the typo3_forum plugin with your pull request. It seems to be working for the most part, except for the issues I mentioned above.

**Comment by kpurrmann** [comment]
Implemented your changes in the next version. Thanks for your work.

**Pull request closed without merging**
